import type { Metadata } from "next";
import { Geist, Rouge_Script } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/AppHeader";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import AppFooter from "@/components/AppFooter";
import { CartProvider } from "@/contexts/CartContext";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rougeScript = Rouge_Script({
  variable: "--font-rouge-script",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body
          className={`${geistSans.className} ${rougeScript.variable} antialiased`}
        >
          <AppHeader />
          {children}
          <AppFooter />
        </body>
      </CartProvider>
    </html>
  );
}
